# =============================================================================
# Inventario - Ambiente: Laboratorio
# Proyecto: Auditoría de configuración de root
# =============================================================================

[laboratorio]
saox1l0mdctlab08
saox1l0mdctlab09
saox1l0mdctlab10
saox1l0mdctlab11

# -----------------------------------------------------------------------------
# Cuando se incorporen otros países, agregar sus grupos aquí:
# [lam_lab]
# [colombia_lab]
# [mexico_lab]
# [peru_lab]
# [chile_lab]
# [brasil_lab]
#
# [laboratorio:children]
# lam_lab
# colombia_lab
# mexico_lab
# peru_lab
# chile_lab
# brasil_lab
# brasil_lab
# -----------------------------------------------------------------------------
